language: java
jdk:
- oraclejdk14
env:
  - TRAVIS_NODE_VERSION="8"
install:
  - sudo apt-get install -y ant ant-optional
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - npm install
script: 
  - export JAVACMD=~/oraclejdk14
  - echo $JAVACMD
  - ant all
sudo: false
after_success:
  - bash <(curl -s https://codecov.io/bash)
deploy:
  provider: pages
  local_dir: javadoc
  skip_cleanup: true
  github_token: $GH_REPO_TOKEN
  keep_history: true
  on:
    branch: master
